#!/bin/bash
if ! grep 'pam_tid.so' /etc/pam.d/sudo --silent; then
  sed -i -e '1s;^;auth       sufficient     pam_tid.so\n;' /etc/pam.d/sudo
fi
if [[ -x /opt/local/lib/pam/pam_reattach.so ]] && ! grep -e '^[^#].*pam_reattach.so$' /etc/pam.d/sudo --silent; then
  sed -i -e '1s;^;auth       optional     /opt/local/lib/pam/pam_reattach.so\n;' /etc/pam.d/sudo
fi
